[package]
name = "symfreq"
version = "0.1.0"
edition = "2024"

[dependencies]
ignore = "0.4.23"
clap = { version = "4", features = ["derive"] }
tabled = { version = "0.20.0", features = ["ansi"] }

[dev-dependencies]
tempfile = "3.23.0"
