[package]
name = "symfreq-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
symfreq = { path = "../symfreq" }
tabled = { version = "0.20.0", features = ["ansi"] }
